### ISSUE TITLE
Crash when trying to create new license file

### ISSUE THREAD

**Issue by GoryMoon** [FatihBozik/license-generator-intellij-plugin#5]
When trying to create a license file the plugin crashes with this log https://gist.github.com/GoryMoon/a7c3c68808bc6107a432e79513b8a9f6

What I'm using
- JetBrains Rider 2020.2.2
- Build #RD-202.6948.24, built on September 9, 2020
- Runtime version: 11.0.8+10-b944.31 amd64
- VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
- .NET Framework 4.0.30319.42000
- Windows 10 10.0

**Comment by blankdvth** [comment]
Also happening for me on PyCharm. Very similar log to GoryMoon's.

- PyCharm Professional 2020.2.1
- PyCharm 2020.2.1 (Professional Edition)
- Build #PY-202.6948.78, built on August 25, 2020
- Runtime version: 11.0.8+10-b944.31 amd64
- VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
- Windows 10 10.0

**Comment by FatihBozik** [comment]
Hi,

Fixed by this [commit](https://github.com/FatihBozik/license-generator-intellij-plugin/commit/5454548ff8bbf7b9bd99ac7ecc415c90292d28da). The new version will be live after JetBrains approval.
If you don't want to wait, you can manually download version latest from the [link](https://github.com/FatihBozik/license-generator-intellij-plugin/releases/tag/v0.0.10).

Download `license-generator-intellij-plugin.zip` file and install it manually using 
Preferences > Plugins > Install plugin from disk…​ and Restart IDE.
