### ISSUE TITLE
Incompatible with the IDEA 2020.3

### ISSUE THREAD

**Issue by 8ar10der** [FatihBozik/license-generator-intellij-plugin#7]
Error message: `Plugin 'License Generator' (version '0.0.10') is not compatible with the current version of the IDE, because it requires build 202.* or older but the current build is IU-203.5981.155`

**Comment by FatihBozik** [comment]
Hi @amaothree,

Thanks for your feedback. Fixed by 0.0.11 version. The new version will be live after JetBrains approval.
If you don't want to wait, you can manually download version latest from the [link](https://github.com/FatihBozik/license-generator-intellij-plugin/releases/tag/v0.0.11). 

Download `license-generator-intellij-plugin-0.0.11.zip` file and install it manually using Preferences > Plugins > 
Install plugin from disk…​ and Restart IDE.
