### ISSUE TITLE
Compatibility Issue with latest stable release of PyCharm

### ISSUE THREAD

**Issue by digital-idiot** [FatihBozik/license-generator-intellij-plugin#8]
The latest release is incompatible with latest PyCharm (Build: `211.6693.115`)

```
Plugin error: Plugin 'License Generator' (version '0.0.11') is not compatible with the current version of the IDE, because it requires build 203.* or older but the current build is PC-211.6693.115
```

**Comment by FatihBozik** [comment]
Fixed by 0.0.12 version. The new version will be live after JetBrains approval. If you don't want to wait, you can manually download latest version from the [link](https://github.com/FatihBozik/license-generator-intellij-plugin/releases/tag/v0.0.12).

Download `license-generator-intellij-plugin-0.0.12.zip` file and install it manually using Preferences > Plugins >
Install plugin from disk and Restart IDE
